CREATE TABLE tbl_cash_flow (
  id int UNSIGNED NOT NULL,
  month_int INT DEFAULT 0 NOT NULL,
  year_int INT DEFAULT 0 NOT NULL,
  costs_int INT DEFAULT 0 NOT NULL,
  income_int INT DEFAULT 0 NOT NULL,
  balance_int INT DEFAULT 0 NULL
  
);

ALTER TABLE tbl_cash_flow
  ADD PRIMARY KEY (id);

ALTER TABLE tbl_cash_flow
  MODIFY id int UNSIGNED NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=1;